<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

class Home extends MY_Controller
{ 
    public function __construct()
    {
        parent::__construct();
       // $this->session->set_userdata('kode_vendor', '512');
    }
    
    function index() {
         $this->session->userdata('kode_vendor');   
         
         // Undangan Pengadaan
         
         $sql = "SELECT KODE_TENDER, KODE_KANTOR ";
         $sql .= " FROM  ";
		 $sql .= " ( SELECT
	TV.KODE_VENDOR
	,T.KODE_TENDER
	,T.JUDUL_PEKERJAAN
	,T.KODE_KANTOR
	,P.TGL_PEMBUKAAN_REG
	,P.TGL_PENUTUPAN_REG
	,
	CASE
	WHEN P.TGL_LELANG_TEKNIS IS NULL  THEN  P.TGL_LELANG_KOMODITI
	ELSE P.TGL_LELANG_TEKNIS
	END AS TGL_LELANG
	, COALESCE(S.NAMA_STATUS, 'Pendaftaran') AS  NAMA_STATUS
	, COALESCE(PTVS.STATUS,1) AS PTVS_STATUS
	, K.KODE_AKTIFITAS
FROM EP_PGD_TENDER T
INNER JOIN EP_PGD_KOMENTAR_TENDER K ON T.KODE_TENDER = K.KODE_TENDER AND T.KODE_KANTOR = K.KODE_KANTOR
INNER JOIN EP_PGD_PERSIAPAN_TENDER P ON T.KODE_TENDER = P.KODE_TENDER AND T.KODE_KANTOR = P.KODE_KANTOR
INNER JOIN EP_PGD_TENDER_VENDOR TV ON T.KODE_TENDER = TV.KODE_TENDER AND T.KODE_KANTOR = TV.KODE_KANTOR
LEFT JOIN EP_PGD_TENDER_VENDOR_STATUS PTVS ON TV.KODE_TENDER = PTVS.KODE_TENDER AND TV.KODE_KANTOR = PTVS.KODE_KANTOR AND TV.KODE_VENDOR = PTVS.KODE_VENDOR
LEFT JOIN EP_PGD_STATUS S ON PTVS.STATUS = S.KODE_STATUS
WHERE     (K.TGL_BERAKHIR IS NULL)

UNION ALL
SELECT
	TV.KODE_VENDOR
	,T.KODE_TENDER
	,T.JUDUL_PEKERJAAN
	,T.KODE_KANTOR
	,P.TGL_PEMBUKAAN_REG
	,P.TGL_PENUTUPAN_REG
	,
	CASE
	WHEN P.TGL_LELANG_TEKNIS IS NULL  THEN  P.TGL_LELANG_KOMODITI
	ELSE P.TGL_LELANG_TEKNIS
	END AS TGL_LELANG
	, COALESCE(S.NAMA_STATUS, 'Pendaftaran') AS  NAMA_STATUS
	, COALESCE(PTVS.STATUS,1) AS PTVS_STATUS
	, K.KODE_AKTIFITAS
FROM EP_PGD_TENDER T
INNER JOIN EP_PGD_KOMENTAR_TENDER K ON T.KODE_TENDER = K.KODE_TENDER AND T.KODE_KANTOR = K.KODE_KANTOR
INNER JOIN EP_PGD_PERSIAPAN_TENDER P ON T.KODE_TENDER = P.KODE_TENDER AND T.KODE_KANTOR = P.KODE_KANTOR
INNER JOIN EP_PGD_TENDER_VENDOR TV ON T.KODE_TENDER = TV.KODE_TENDER AND T.KODE_KANTOR = TV.KODE_KANTOR
LEFT JOIN EP_PGD_TENDER_VENDOR_STATUS PTVS ON TV.KODE_TENDER = PTVS.KODE_TENDER AND TV.KODE_KANTOR = PTVS.KODE_KANTOR AND TV.KODE_VENDOR = PTVS.KODE_VENDOR
LEFT JOIN EP_PGD_STATUS S ON PTVS.STATUS = S.KODE_STATUS
WHERE     (K.TGL_BERAKHIR IS NULL)
		   AND (K.KODE_AKTIFITAS IN (1205, 1206, 1305, 1306, 1402, 1403, 1502, 1503, 1507, 1508, 1605, 1606, 1702, 1703))
		   AND (P.TGL_LELANG_KOMODITI >=  SYSDATE)
		   AND (S.KODE_STATUS IN (2, 3, 5, 20, 21))
UNION ALL
SELECT
	TV.KODE_VENDOR
	,T.KODE_TENDER
	,T.JUDUL_PEKERJAAN
	,T.KODE_KANTOR
	,P.TGL_PEMBUKAAN_REG
	,P.TGL_PENUTUPAN_REG
	,
	CASE
	WHEN P.TGL_LELANG_TEKNIS IS NULL  THEN  P.TGL_LELANG_KOMODITI
	ELSE P.TGL_LELANG_TEKNIS
	END AS TGL_LELANG
	, COALESCE(S.NAMA_STATUS, 'Pendaftaran') AS  NAMA_STATUS
	, COALESCE(PTVS.STATUS,1) AS PTVS_STATUS
	, K.KODE_AKTIFITAS
FROM EP_PGD_TENDER T
INNER JOIN EP_PGD_KOMENTAR_TENDER K ON T.KODE_TENDER = K.KODE_TENDER AND T.KODE_KANTOR = K.KODE_KANTOR
INNER JOIN EP_PGD_PERSIAPAN_TENDER P ON T.KODE_TENDER = P.KODE_TENDER AND T.KODE_KANTOR = P.KODE_KANTOR
INNER JOIN EP_PGD_TENDER_VENDOR TV ON T.KODE_TENDER = TV.KODE_TENDER AND T.KODE_KANTOR = TV.KODE_KANTOR
LEFT JOIN EP_PGD_TENDER_VENDOR_STATUS PTVS ON TV.KODE_TENDER = PTVS.KODE_TENDER AND TV.KODE_KANTOR = PTVS.KODE_KANTOR AND TV.KODE_VENDOR = PTVS.KODE_VENDOR
LEFT JOIN EP_PGD_STATUS S ON PTVS.STATUS = S.KODE_STATUS
WHERE     (K.TGL_BERAKHIR IS NULL)
		   AND (K.KODE_AKTIFITAS IN (1205, 1206, 1305, 1306, 1402, 1403, 1502, 1503, 1507, 1508, 1605, 1606, 1702, 1703))
		   AND (P.TGL_PEMBUKAAN_LELANG >=  SYSDATE)
		   AND (S.KODE_STATUS IN (2, 3, 5, 20, 21))
UNION ALL
SELECT
	TV.KODE_VENDOR
	,T.KODE_TENDER
	,T.JUDUL_PEKERJAAN
	,T.KODE_KANTOR
	,P.TGL_PEMBUKAAN_REG
	,P.TGL_PENUTUPAN_REG
	,
	CASE
	WHEN P.TGL_LELANG_TEKNIS IS NULL  THEN  P.TGL_LELANG_KOMODITI
	ELSE P.TGL_LELANG_TEKNIS
	END AS TGL_LELANG
	, COALESCE(S.NAMA_STATUS, 'Pendaftaran') AS  NAMA_STATUS
	, COALESCE(PTVS.STATUS,1) AS PTVS_STATUS
	, K.KODE_AKTIFITAS
FROM EP_PGD_TENDER T
INNER JOIN EP_PGD_KOMENTAR_TENDER K ON T.KODE_TENDER = K.KODE_TENDER AND T.KODE_KANTOR = K.KODE_KANTOR
INNER JOIN EP_PGD_PERSIAPAN_TENDER P ON T.KODE_TENDER = P.KODE_TENDER AND T.KODE_KANTOR = P.KODE_KANTOR
INNER JOIN EP_PGD_TENDER_VENDOR TV ON T.KODE_TENDER = TV.KODE_TENDER AND T.KODE_KANTOR = TV.KODE_KANTOR
LEFT JOIN EP_PGD_TENDER_VENDOR_STATUS PTVS ON TV.KODE_TENDER = PTVS.KODE_TENDER AND TV.KODE_KANTOR = PTVS.KODE_KANTOR AND TV.KODE_VENDOR = PTVS.KODE_VENDOR
LEFT JOIN EP_PGD_STATUS S ON PTVS.STATUS = S.KODE_STATUS
WHERE     (K.TGL_BERAKHIR IS NULL)
		   AND (K.KODE_AKTIFITAS IN (1205, 1206, 1305, 1306, 1402, 1403, 1502, 1503, 1507, 1508, 1605, 1606, 1702, 1703))
		   AND (P.TGL_LELANG_TEKNIS >=  SYSDATE)
		   AND (S.KODE_STATUS IN (2, 3, 5, 20, 21))
 
UNION ALL
SELECT
	TV.KODE_VENDOR
	,T.KODE_TENDER
	,T.JUDUL_PEKERJAAN
	,T.KODE_KANTOR
	,P.TGL_PEMBUKAAN_REG
	,P.TGL_PENUTUPAN_REG
	,
	CASE
	WHEN P.TGL_LELANG_TEKNIS IS NULL  THEN  P.TGL_LELANG_KOMODITI
	ELSE P.TGL_LELANG_TEKNIS
	END AS TGL_LELANG
	, COALESCE(S.NAMA_STATUS, 'Pendaftaran') AS  NAMA_STATUS
	, COALESCE(PTVS.STATUS,1) AS PTVS_STATUS
	, K.KODE_AKTIFITAS
FROM EP_PGD_TENDER T
INNER JOIN EP_PGD_KOMENTAR_TENDER K ON T.KODE_TENDER = K.KODE_TENDER AND T.KODE_KANTOR = K.KODE_KANTOR
INNER JOIN EP_PGD_PERSIAPAN_TENDER P ON T.KODE_TENDER = P.KODE_TENDER AND T.KODE_KANTOR = P.KODE_KANTOR
INNER JOIN EP_PGD_TENDER_VENDOR TV ON T.KODE_TENDER = TV.KODE_TENDER AND T.KODE_KANTOR = TV.KODE_KANTOR
LEFT JOIN EP_PGD_TENDER_VENDOR_STATUS PTVS ON TV.KODE_TENDER = PTVS.KODE_TENDER AND TV.KODE_KANTOR = PTVS.KODE_KANTOR AND TV.KODE_VENDOR = PTVS.KODE_VENDOR
LEFT JOIN EP_PGD_STATUS S ON PTVS.STATUS = S.KODE_STATUS
WHERE     (K.TGL_BERAKHIR IS NULL)
		   AND (K.KODE_AKTIFITAS IN (1209,1309, 1407, 1511, 1610, 1706))
		   AND (P.TGL_LELANG_TEKNIS >=  SYSDATE)
		   AND (S.KODE_STATUS = 10 )) VW_PGD_PEKERJAAN_VENDOR  "; 
         $sql .= " WHERE KODE_VENDOR =  " . $this->session->userdata('kode_vendor');   
         $sql .= " AND PTVS_STATUS = 1";   
         
          
         $query = $this->db->query($sql);
         $result = $query->result(); 
          
         $data["cnt_undangan"] = count($result);
         
         $sql = "SELECT KODE_TENDER, KODE_KANTOR ";
         $sql .= " FROM EP_PGD_TENDER_VENDOR_STATUS ";
         $sql .= " WHERE KODE_VENDOR =  " . $this->session->userdata('kode_vendor');   
         $sql .= " AND STATUS in  (2,20) ";   
         
         $query = $this->db->query($sql);
         $result = $query->result(); 
         $data["cnt_tunggu_penawaran"] = count($result);
         
         
         $sql = "SELECT KODE_TENDER, KODE_KANTOR ";
         $sql .= " FROM EP_PGD_TENDER_VENDOR_STATUS ";
         $sql .= " WHERE KODE_VENDOR =  " . $this->session->userdata('kode_vendor');   
         $sql .= " AND STATUS in  (3,21) ";   
         
         $query = $this->db->query($sql);
         $result = $query->result(); 
         $data["cnt_sudah_kirim_penawaran"] = count($result);
         
         
         $sql = "SELECT KODE_TENDER, KODE_KANTOR ";
         $sql .= " FROM EP_PGD_TENDER_VENDOR_STATUS ";
         $sql .= " WHERE KODE_VENDOR =  " . $this->session->userdata('kode_vendor');   
         $sql .= " AND STATUS in  (11) ";   
         
         $query = $this->db->query($sql);
         $result = $query->result(); 
         $data["cnt_award"] = count($result);
         
         
         $sql = "SELECT KODE_TENDER, KODE_KANTOR ";
         $sql .= " FROM EP_PGD_TENDER_VENDOR_STATUS ";
         $sql .= " WHERE KODE_VENDOR =  " . $this->session->userdata('kode_vendor');   
         $sql .= " AND STATUS in  (10) ";   
         
         $query = $this->db->query($sql);
         $result = $query->result(); 
         $data["cnt_negosiasi"] = count($result);
         
         
         
         $this->layout->view('home', $data);
    }
    
    
}
